#!/bin/sh
#
# Set up everything on this Mac, or bring it up to date.
#
#     npm run install:mac
#
# Idempotent: run it again after a `git pull` and it rebuilds, reinstalls and
# reloads. That is the whole point — the alternative was eight steps, two plists
# with paths to hand-edit, and four launchctl invocations, which is a setup nobody
# performs correctly on the second machine.
#
# What it does, and each one is reported as it happens:
#
#   1. builds the bundle and the browser client
#   2. puts `guildhall` on your PATH
#   3. installs and loads the headless service, so the browser view survives a reboot
#   4. builds and installs the menu bar app
#   5. installs and loads the menu bar app's login agent
#
# It does NOT set a passcode or a control password. Those are credentials and they
# are chosen, not generated by an installer.
set -eu
cd "$(dirname "$0")/.."

say() { printf '\n\033[1m%s\033[0m\n' "$1"; }
ok() { printf '  ✓ %s\n' "$1"; }
warn() { printf '  ! %s\n' "$1"; }

AGENTS="$HOME/Library/LaunchAgents"
LOGS="$HOME/Library/Logs"
UID_NUM=$(id -u)
mkdir -p "$AGENTS" "$LOGS"

say "Building"
npm run --silent build
ok "dist/main.mjs and web/app.js"

say "Putting guildhall on your PATH"
if npm link >/dev/null 2>&1; then
	ok "$(command -v guildhall || echo 'linked')"
else
	warn "npm link failed — run it yourself, or use ./bin/guildhall"
fi

# The plists carry /Users/CHANGEME so the repo holds no machine's paths. Both are
# substituted here, which is the one place that knows this machine.
install_agent() {
	label="$1"
	src="contrib/$label.plist"
	dest="$AGENTS/$label.plist"
	sed -e "s|/Users/CHANGEME/.nvm/versions/node/v22.0.0/bin/node|$NODE|g" \
		-e "s|/Users/CHANGEME/projects/guildhall|$PWD|g" \
		-e "s|/Users/CHANGEME|$HOME|g" \
		"$src" > "$dest"
	plutil -lint "$dest" >/dev/null
	# bootout first: launchd caches the job definition, so a plist edit alone
	# changes nothing about a job it is already holding.
	launchctl bootout "gui/$UID_NUM/$label" 2>/dev/null || true
	launchctl bootstrap "gui/$UID_NUM" "$dest"
	ok "$label loaded"
}

NODE=$(command -v node || true)
[ -n "$NODE" ] || { echo "node is not on your PATH" >&2; exit 1; }

say "The browser view, as a service"
install_agent dev.guildhall.headless
sleep 2
PORT=$(node -p "try{require(process.env.HOME+'/.config/guildhall/config.json').port}catch(e){4318}")
CODE=$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/" || true)
case "$CODE" in
401) ok "answering on port $PORT (401 is the passcode gate, which means it is up)" ;;
000) warn "nothing answering on port $PORT yet — check $LOGS/guildhall-headless.log" ;;
*) ok "answering on port $PORT (HTTP $CODE)" ;;
esac
# The common cause, and the one that produced 1,366 restarts on the author's
# machine: an interactive room started earlier already owns the port.
if pgrep -f 'dist/main.mjs$' >/dev/null 2>&1; then
	warn "a guildhall room is also running and may be holding port $PORT — quit it with q"
fi

if command -v swift >/dev/null 2>&1; then
	say "The menu bar app"
	sh swift/build.sh --install >/dev/null
	ok "/Applications/GuildhallBar.app"
	install_agent dev.guildhall.bar
	sleep 3
	if pgrep -x GuildhallBar >/dev/null; then
		ok "running — look for the hall icon in your menu bar"
	else
		warn "did not start — check $LOGS/guildhall-bar.log"
	fi
else
	say "The menu bar app"
	warn "no swift toolchain, skipping it (install Xcode, then run this again)"
fi

say "Done"
cat <<'NEXT'
  guildhall              watch the room in a terminal (optional)
  guildhall --help       everything it can do
  ? in the room          the address and passcode for your phone

  The browser view and the menu bar icon now start at login. To stop either:
    launchctl bootout gui/$(id -u)/dev.guildhall.headless
    launchctl bootout gui/$(id -u)/dev.guildhall.bar
NEXT
