#!/bin/sh
#
# Set up everything on this Mac, or bring it up to date.
#
#     npm run install:mac
#
# Idempotent: run it again after a `git pull` and it rebuilds, reinstalls and
# reloads. That is the whole point — the alternative was eight steps, two plists
# with paths to hand-edit, and four launchctl invocations, which is a setup nobody
# performs correctly on the second machine.
#
# What it does, and each one is reported as it happens:
#
#   1. builds the bundle and the browser client
#   2. puts `guildhall` on your PATH
#   3. installs and loads the headless service, so the browser view survives a reboot
#   4. builds and installs the menu bar app
#   5. installs and loads the menu bar app's login agent
#
# It does NOT set a passcode or a control password. Those are credentials and they
# are chosen, not generated by an installer.
#
# What it DOES do, which is worth saying out loud because the README calls the
# server "off by default": `--headless` turns serving on unconditionally and binds
# 0.0.0.0, so after this the machine answers on your LAN and on every VPN interface,
# behind a four-digit passcode that is auto-generated and that you have not seen
# yet. Run `guildhall` and press `?` to read it. Use --guard instead if you want the
# sleep-holding behavior without a server.
set -eu
cd "$(dirname "$0")/.."

# `--guard` installs the sleep-holding agent INSTEAD of the browser service. Both
# hold sleep off, so installing both would be two jobs doing one job's work. The
# guard plist had no install path at all before this and told the reader to edit it
# by hand, which is how it kept a node path that exists on almost no machine.
WANT_GUARD=no
for a in "$@"; do
	case "$a" in
	--guard) WANT_GUARD=yes ;;
	*) echo "unknown option: $a (only --guard)" >&2; exit 2 ;;
	esac
done

say() { printf '\n\033[1m%s\033[0m\n' "$1"; }
ok() { printf '  ✓ %s\n' "$1"; }
warn() { printf '  ! %s\n' "$1"; }

AGENTS="$HOME/Library/LaunchAgents"
LOGS="$HOME/Library/Logs"
UID_NUM=$(id -u)
mkdir -p "$AGENTS" "$LOGS"

say "Building"
npm run --silent build
ok "dist/main.mjs and web/app.js"

say "Putting guildhall on your PATH"
if npm link >/dev/null 2>&1; then
	ok "$(command -v guildhall || echo 'linked')"
else
	warn "npm link failed — run it yourself, or use ./bin/guildhall"
fi

# `&` in a sed REPLACEMENT means the whole match, and `|` ends the expression. So a
# checkout at ~/R&D/guildhall produced
#   /Users/j/R/Users/j/projects/guildhallD/guildhall/dist/main.mjs
# which plutil accepts — it is a valid string — so the lint below did not catch it,
# the job silently failed to spawn, and the only symptom was "nothing answering".
# A path containing `|` made sed itself fail and aborted the installer mid-way.
esc() { printf '%s' "$1" | sed -e 's/[&|\\]/\\&/g'; }

# The plists carry placeholders so the repo holds no machine's paths. Every one is
# substituted here, which is the one place that knows this machine.
install_agent() {
	label="$1"
	src="contrib/$label.plist"
	dest="$AGENTS/$label.plist"
	sed -e "s|/CHANGEME-NODE|$(esc "$NODE")|g" \
		-e "s|/Users/CHANGEME/projects/guildhall|$(esc "$PWD")|g" \
		-e "s|/Users/CHANGEME|$(esc "$HOME")|g" \
		"$src" > "$dest"
	# Nothing may reach launchd still carrying a placeholder. plutil only checks that
	# the file is valid plist, which a wrong path is.
	if grep -q 'CHANGEME' "$dest"; then
		echo "  ! $label still contains a placeholder after substitution — not loading it" >&2
		grep -n 'CHANGEME' "$dest" >&2
		exit 1
	fi
	plutil -lint "$dest" >/dev/null
	# bootout first: launchd caches the job definition, so a plist edit alone
	# changes nothing about a job it is already holding.
	launchctl bootout "gui/$UID_NUM/$label" 2>/dev/null || true
	launchctl bootstrap "gui/$UID_NUM" "$dest"
	ok "$label loaded"
}

NODE=$(command -v node || true)
[ -n "$NODE" ] || { echo "node is not on your PATH" >&2; exit 1; }

if [ "$WANT_GUARD" = yes ]; then
	say "The sleep guard, as a service (no server)"
	install_agent dev.guildhall.guard
	say "Done"
	echo "  guildhall --guard     the same thing in a terminal, with a log on screen"
	echo "  To stop it:  launchctl bootout gui/$UID_NUM/dev.guildhall.guard"
	exit 0
fi

say "The browser view, as a service"
install_agent dev.guildhall.headless
sleep 2
# `?? 4318` as well as the catch: the catch covers a missing or corrupt file, but a
# file WITHOUT a port key returned the string "undefined", so this curled
# http://127.0.0.1:undefined/ and reported "nothing answering on port undefined"
# for a service that was running fine. src/config.ts defaults it to 4318; match that.
PORT=$(node -p "try{require(process.env.HOME+'/.config/guildhall/config.json').port ?? 4318}catch(e){4318}")
CODE=$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/" || true)
case "$CODE" in
401) ok "answering on port $PORT (401 is the passcode gate, which means it is up)" ;;
000) warn "nothing answering on port $PORT yet — check $LOGS/guildhall-headless.log" ;;
*) ok "answering on port $PORT (HTTP $CODE)" ;;
esac
# The common cause, and the one that produced 1,366 restarts on the author's
# machine: an interactive room started earlier already owns the port.
if pgrep -f 'dist/main.mjs$' >/dev/null 2>&1; then
	warn "a guildhall room is also running and may be holding port $PORT — quit it with q"
fi

# `command -v swift` is not the same question as "can it build". Command Line Tools
# alone provide the swift binary while `swift build` fails for want of an SDK, and
# `set -e` then killed the installer here — AFTER the headless agent was loaded, so
# the summary never printed and the user was told nothing.
# stdout is noise (compile progress); stderr is not — it carries "could not build
# the app icon" and any real build error. Swallowing both meant a bundle could land
# in /Applications with no icon and nothing said so.
if command -v swift >/dev/null 2>&1 && sh swift/build.sh --install >/dev/null; then
	say "The menu bar app"
	ok "/Applications/GuildhallBar.app"
	install_agent dev.guildhall.bar
	sleep 3
	if pgrep -x GuildhallBar >/dev/null; then
		ok "running — look for the hall icon in your menu bar"
	else
		warn "did not start — check $LOGS/guildhall-bar.log"
	fi
else
	say "The menu bar app"
	if command -v swift >/dev/null 2>&1; then
		warn "swift is present but the build failed — for the reason, run: sh swift/build.sh"
		warn "usually a Command Line Tools install without a full SDK: sudo xcode-select --switch /Applications/Xcode.app"
	else
		warn "no swift toolchain, skipping it (install Xcode, then run this again)"
	fi
fi

say "Done"
cat <<'NEXT'
  guildhall              watch the room in a terminal (optional)
  guildhall --help       everything it can do
  ? in the room          the address and passcode for your phone

  The browser view is now reachable from your LAN and any VPN interface, behind
  the passcode above. `guildhall --set-passcode NNNN` changes it; turning sharing
  off entirely is `serve: false` in ~/.config/guildhall/config.json, but the
  headless service overrides that by design — bootout the agent to stop serving.

  The browser view and the menu bar icon now start at login. To stop either:
    launchctl bootout gui/$(id -u)/dev.guildhall.headless
    launchctl bootout gui/$(id -u)/dev.guildhall.bar
NEXT
