#!/bin/sh
#
# Set up everything on this Mac, or bring it up to date.
#
#     npm run install:mac
#
# Idempotent: run it again after a `git pull` and it rebuilds, reinstalls and
# reloads. That is the whole point — the alternative was eight steps, two plists
# with paths to hand-edit, and four launchctl invocations, which is a setup nobody
# performs correctly on the second machine.
#
# What it does, and each one is reported as it happens:
#
#   1. builds the bundle and the browser client
#   2. puts `guildhall` on your PATH
#   3. (only with --serve) installs the headless service for the browser view
#   4. builds and installs the menu bar app
#   5. installs and loads the menu bar app's login agent
#
# It does NOT set a passcode or a control password. Those are credentials and they
# are chosen, not generated by an installer.
#
# It does NOT start serving the browser view, and that is the point. It used to,
# which meant installing a menu bar app turned the machine into a server answering
# on every interface for data nobody had chosen to share. The app reads the room by
# running `guildhall --sessions` — no server, no port, no passcode involved.
#
#   --serve   also install the browser view as a login service
#   --guard   install the sleep-holder instead (no server, no browser view)
#
# Even with --serve it binds loopback only until you pick "the network" in the menu
# bar settings, which is the same setting written to the same config file.
set -eu
cd "$(dirname "$0")/.."

# `--guard` installs the sleep-holding agent INSTEAD of the browser service. Both
# hold sleep off, so installing both would be two jobs doing one job's work. The
# guard plist had no install path at all before this and told the reader to edit it
# by hand, which is how it kept a node path that exists on almost no machine.
WANT_GUARD=no
WANT_SERVE=no
for a in "$@"; do
	case "$a" in
	--guard) WANT_GUARD=yes ;;
	--serve) WANT_SERVE=yes ;;
	*) echo "unknown option: $a (only --guard or --serve)" >&2; exit 2 ;;
	esac
done

say() { printf '\n\033[1m%s\033[0m\n' "$1"; }
ok() { printf '  ✓ %s\n' "$1"; }
warn() { printf '  ! %s\n' "$1"; }

AGENTS="$HOME/Library/LaunchAgents"
LOGS="$HOME/Library/Logs"
UID_NUM=$(id -u)
mkdir -p "$AGENTS" "$LOGS"

# The commit gates, which are per-CLONE and off by default.
#
# `core.hooksPath` is repository-local and git does not carry it across a clone, so
# a fresh checkout has NO pre-commit checks at all — not the privacy gate, not
# secrets, not spelling, not the perf budget. That is the wrong default on a machine
# somebody is about to commit from, and it is not something you remember to do.
if [ -d .git ]; then
	say "Commit gates"
	npm run --silent hooks
	ok "pre-commit, commit-msg, pre-merge-commit and pre-push are active in this clone"
fi

say "Building"
npm run --silent build
ok "dist/main.mjs and web/app.js"

say "Putting guildhall on your PATH"
if npm link >/dev/null 2>&1; then
	ok "$(command -v guildhall || echo 'linked')"
else
	warn "npm link failed — run it yourself, or use ./bin/guildhall"
fi

# `&` in a sed REPLACEMENT means the whole match, and `|` ends the expression. So a
# checkout at ~/R&D/guildhall produced
#   /Users/j/R/Users/j/projects/guildhallD/guildhall/dist/main.mjs
# which plutil accepts — it is a valid string — so the lint below did not catch it,
# the job silently failed to spawn, and the only symptom was "nothing answering".
# A path containing `|` made sed itself fail and aborted the installer mid-way.
esc() { printf '%s' "$1" | sed -e 's/[&|\\]/\\&/g'; }

# The plists carry placeholders so the repo holds no machine's paths. Every one is
# substituted here, which is the one place that knows this machine.
install_agent() {
	label="$1"
	src="contrib/$label.plist"
	dest="$AGENTS/$label.plist"
	sed -e "s|/CHANGEME-NODE|$(esc "$NODE")|g" \
		-e "s|/Users/CHANGEME/projects/guildhall|$(esc "$PWD")|g" \
		-e "s|/Users/CHANGEME|$(esc "$HOME")|g" \
		"$src" > "$dest"
	# Nothing may reach launchd still carrying a placeholder. plutil only checks that
	# the file is valid plist, which a wrong path is.
	if grep -q 'CHANGEME' "$dest"; then
		echo "  ! $label still contains a placeholder after substitution — not loading it" >&2
		grep -n 'CHANGEME' "$dest" >&2
		exit 1
	fi
	plutil -lint "$dest" >/dev/null
	# bootout first: launchd caches the job definition, so a plist edit alone
	# changes nothing about a job it is already holding.
	launchctl bootout "gui/$UID_NUM/$label" 2>/dev/null || true
	# And WAIT for it, because bootout is asynchronous. It returns as soon as the
	# request is accepted, not when the job is gone — a GUI app still has to finish
	# quitting. Bootstrapping into that window fails with
	# `Bootstrap failed: 5: Input/output error`, which is launchd's way of saying the
	# label is already loaded, and it failed only for whoever's app was slower to exit.
	n=0
	while launchctl print "gui/$UID_NUM/$label" >/dev/null 2>&1 && [ "$n" -lt 40 ]; do
		sleep 0.25
		n=$((n + 1))
	done
	if launchctl bootstrap "gui/$UID_NUM" "$dest" 2>/dev/null; then
		ok "$label loaded"
	elif launchctl print "gui/$UID_NUM/$label" >/dev/null 2>&1; then
		# Bootstrap refused but the job IS loaded. Saying "failed" here would send
		# somebody debugging a working service.
		ok "$label already loaded (launchd kept the running one)"
	else
		warn "$label could not be loaded — launchctl said:"
		launchctl bootstrap "gui/$UID_NUM" "$dest" 2>&1 | sed 's/^/    /' >&2 || true
		exit 1
	fi
}

NODE=$(command -v node || true)
[ -n "$NODE" ] || { echo "node is not on your PATH" >&2; exit 1; }

if [ "$WANT_GUARD" = yes ]; then
	say "The sleep guard, as a service (no server)"
	install_agent dev.guildhall.guard
	say "Done"
	echo "  guildhall --guard     the same thing in a terminal, with a log on screen"
	echo "  To stop it:  launchctl bootout gui/$UID_NUM/dev.guildhall.guard"
	exit 0
fi

# `command -v swift` is not the same question as "can it build". Command Line Tools
# alone provide the swift binary while `swift build` fails for want of an SDK, and
# `set -e` then killed the installer here — AFTER the headless agent was loaded, so
# the summary never printed and the user was told nothing.
# stdout is noise (compile progress); stderr is not — it carries "could not build
# the app icon" and any real build error. Swallowing both meant a bundle could land
# in /Applications with no icon and nothing said so.
if command -v swift >/dev/null 2>&1 && sh swift/build.sh --install --no-reload >/dev/null; then
	say "The menu bar app"
	ok "/Applications/GuildhallBar.app"
	install_agent dev.guildhall.bar
	sleep 3
	if pgrep -x GuildhallBar >/dev/null; then
		ok "running — look for the hall icon in your menu bar"
	else
		warn "did not start — check $LOGS/guildhall-bar.log"
	fi
else
	say "The menu bar app"
	if command -v swift >/dev/null 2>&1; then
		warn "swift is present but the build failed — for the reason, run: sh swift/build.sh"
		warn "usually a Command Line Tools install without a full SDK: sudo xcode-select --switch /Applications/Xcode.app"
	else
		warn "no swift toolchain, skipping it (install Xcode, then run this again)"
	fi
fi

if [ "$WANT_SERVE" = yes ]; then
	say "The browser view, as a service"
	# `--set-serve on` rather than install_agent: the menu bar toggle calls the same
	# thing, so the plist has one definition instead of one here and another in Swift.
	if node dist/main.mjs --set-serve on; then
		ok "dev.guildhall.headless loaded"
	else
		warn "could not start it — see the message above"
	fi
	sleep 2
	# Ask guildhall, rather than parsing config.json here with a third opinion about
	# the default. This read the file directly and applied its own fallback: a file
	# without a `port` key yielded the string "undefined", so it curled
	# http://127.0.0.1:undefined/ and reported "nothing answering on port undefined"
	# for a service that was running perfectly well.
	PORT=$(node dist/main.mjs --config | node -p "JSON.parse(require('fs').readFileSync(0,'utf8')).port")
	CODE=$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/" || true)
	case "$CODE" in
	401) ok "answering on port $PORT (401 is the passcode gate, which means it is up)" ;;
	000) warn "nothing answering on port $PORT yet — check $LOGS/guildhall-headless.log" ;;
	*) ok "answering on port $PORT (HTTP $CODE)" ;;
	esac
	# The common cause, and the one that produced 1,366 restarts on the author's
	# machine: an interactive room started earlier already owns the port.
	if pgrep -f 'dist/main.mjs$' >/dev/null 2>&1; then
		warn "a guildhall room is also running and may be holding port $PORT — quit it with q"
	fi
else
	say "The browser view"
	echo "  not installed, which is the default now."
	echo ""
	echo "  The menu bar app does not need it: it reads the room by running"
	echo "  \`guildhall --sessions\`, so no server, no port and no passcode are"
	echo "  involved in showing you the icon. Installing an app should not quietly"
	echo "  turn the machine into a server."
	echo ""
	echo "  To serve it — to this machine, or to your phone:"
	echo "    sh tools/install-mac.sh --serve"
	echo "  It is the same setting the menu bar panel exposes, so either works."
	# Saying "not installed" while a service from an earlier run is still serving
	# would be the same kind of untruth as the default that made this necessary.
	if launchctl print "gui/$UID_NUM/dev.guildhall.headless" >/dev/null 2>&1; then
		echo ""
		warn "a browser-view service from an earlier install IS still loaded and serving"
		warn "stop it:   launchctl bootout gui/$UID_NUM/dev.guildhall.headless"
		warn "remove it: rm ~/Library/LaunchAgents/dev.guildhall.headless.plist"
	fi
fi

say "Done"
echo "  guildhall              watch the room in a terminal"
echo "  guildhall --help       everything it can do"
echo ""
if [ "$WANT_SERVE" = yes ]; then
	echo "  ? in the room          the address and passcode for your phone"
	echo ""
	echo "  It binds loopback only until you choose \"the network\" in the menu bar"
	echo "  settings. Choose a passcode if you have not: guildhall --set-passcode NNNN"
	echo ""
	echo "  Both start at login. To stop either:"
	echo "    launchctl bootout gui/$UID_NUM/dev.guildhall.headless"
	echo "    launchctl bootout gui/$UID_NUM/dev.guildhall.bar"
else
	# Do not claim nothing is serving without checking. The warning above already
	# found this case; a summary that contradicts it is worse than no summary.
	if launchctl print "gui/$UID_NUM/dev.guildhall.headless" >/dev/null 2>&1; then
		echo "  This install added no server, but the one noted above is STILL RUNNING."
	else
		echo "  No server is running, and nothing is reachable from the network."
	fi
	echo "  The menu bar icon starts at login. To stop it:"
	echo "    launchctl bootout gui/$UID_NUM/dev.guildhall.bar"
fi
